// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nats-io/nats.go/jetstream (interfaces: KeyValue,KeyValueEntry,KeyWatcher)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
)

// MockJetstreamKeyValue is a mock of KeyValue interface.
type MockJetstreamKeyValue struct {
	ctrl     *gomock.Controller
	recorder *MockJetstreamKeyValueMockRecorder
}

// MockJetstreamKeyValueMockRecorder is the mock recorder for MockJetstreamKeyValue.
type MockJetstreamKeyValueMockRecorder struct {
	mock *MockJetstreamKeyValue
}

// NewMockJetstreamKeyValue creates a new mock instance.
func NewMockJetstreamKeyValue(ctrl *gomock.Controller) *MockJetstreamKeyValue {
	mock := &MockJetstreamKeyValue{ctrl: ctrl}
	mock.recorder = &MockJetstreamKeyValueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJetstreamKeyValue) EXPECT() *MockJetstreamKeyValueMockRecorder {
	return m.recorder
}

// Bucket mocks base method.
func (m *MockJetstreamKeyValue) Bucket() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bucket")
	ret0, _ := ret[0].(string)
	return ret0
}

// Bucket indicates an expected call of Bucket.
func (mr *MockJetstreamKeyValueMockRecorder) Bucket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bucket", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Bucket))
}

// Create mocks base method.
func (m *MockJetstreamKeyValue) Create(arg0 context.Context, arg1 string, arg2 []byte, arg3 ...jetstream.KVCreateOpt) (uint64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockJetstreamKeyValueMockRecorder) Create(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockJetstreamKeyValue) Delete(arg0 context.Context, arg1 string, arg2 ...jetstream.KVDeleteOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJetstreamKeyValueMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockJetstreamKeyValue) Get(arg0 context.Context, arg1 string) (jetstream.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(jetstream.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJetstreamKeyValueMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Get), arg0, arg1)
}

// GetRevision mocks base method.
func (m *MockJetstreamKeyValue) GetRevision(arg0 context.Context, arg1 string, arg2 uint64) (jetstream.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevision", arg0, arg1, arg2)
	ret0, _ := ret[0].(jetstream.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevision indicates an expected call of GetRevision.
func (mr *MockJetstreamKeyValueMockRecorder) GetRevision(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevision", reflect.TypeOf((*MockJetstreamKeyValue)(nil).GetRevision), arg0, arg1, arg2)
}

// History mocks base method.
func (m *MockJetstreamKeyValue) History(arg0 context.Context, arg1 string, arg2 ...jetstream.WatchOpt) ([]jetstream.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "History", varargs...)
	ret0, _ := ret[0].([]jetstream.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockJetstreamKeyValueMockRecorder) History(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockJetstreamKeyValue)(nil).History), varargs...)
}

// Keys mocks base method.
func (m *MockJetstreamKeyValue) Keys(arg0 context.Context, arg1 ...jetstream.WatchOpt) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Keys", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keys indicates an expected call of Keys.
func (mr *MockJetstreamKeyValueMockRecorder) Keys(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Keys), varargs...)
}

// ListKeys mocks base method.
func (m *MockJetstreamKeyValue) ListKeys(arg0 context.Context, arg1 ...jetstream.WatchOpt) (jetstream.KeyLister, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListKeys", varargs...)
	ret0, _ := ret[0].(jetstream.KeyLister)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeys indicates an expected call of ListKeys.
func (mr *MockJetstreamKeyValueMockRecorder) ListKeys(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeys", reflect.TypeOf((*MockJetstreamKeyValue)(nil).ListKeys), varargs...)
}

// ListKeysFiltered mocks base method.
func (m *MockJetstreamKeyValue) ListKeysFiltered(arg0 context.Context, arg1 ...string) (jetstream.KeyLister, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListKeysFiltered", varargs...)
	ret0, _ := ret[0].(jetstream.KeyLister)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeysFiltered indicates an expected call of ListKeysFiltered.
func (mr *MockJetstreamKeyValueMockRecorder) ListKeysFiltered(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeysFiltered", reflect.TypeOf((*MockJetstreamKeyValue)(nil).ListKeysFiltered), varargs...)
}

// Purge mocks base method.
func (m *MockJetstreamKeyValue) Purge(arg0 context.Context, arg1 string, arg2 ...jetstream.KVDeleteOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Purge", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Purge indicates an expected call of Purge.
func (mr *MockJetstreamKeyValueMockRecorder) Purge(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Purge), varargs...)
}

// PurgeDeletes mocks base method.
func (m *MockJetstreamKeyValue) PurgeDeletes(arg0 context.Context, arg1 ...jetstream.KVPurgeOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PurgeDeletes", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgeDeletes indicates an expected call of PurgeDeletes.
func (mr *MockJetstreamKeyValueMockRecorder) PurgeDeletes(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeDeletes", reflect.TypeOf((*MockJetstreamKeyValue)(nil).PurgeDeletes), varargs...)
}

// Put mocks base method.
func (m *MockJetstreamKeyValue) Put(arg0 context.Context, arg1 string, arg2 []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockJetstreamKeyValueMockRecorder) Put(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Put), arg0, arg1, arg2)
}

// PutString mocks base method.
func (m *MockJetstreamKeyValue) PutString(arg0 context.Context, arg1, arg2 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutString", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutString indicates an expected call of PutString.
func (mr *MockJetstreamKeyValueMockRecorder) PutString(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutString", reflect.TypeOf((*MockJetstreamKeyValue)(nil).PutString), arg0, arg1, arg2)
}

// Status mocks base method.
func (m *MockJetstreamKeyValue) Status(arg0 context.Context) (jetstream.KeyValueStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0)
	ret0, _ := ret[0].(jetstream.KeyValueStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockJetstreamKeyValueMockRecorder) Status(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Status), arg0)
}

// Update mocks base method.
func (m *MockJetstreamKeyValue) Update(arg0 context.Context, arg1 string, arg2 []byte, arg3 uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockJetstreamKeyValueMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Update), arg0, arg1, arg2, arg3)
}

// Watch mocks base method.
func (m *MockJetstreamKeyValue) Watch(arg0 context.Context, arg1 string, arg2 ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(jetstream.KeyWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockJetstreamKeyValueMockRecorder) Watch(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockJetstreamKeyValue)(nil).Watch), varargs...)
}

// WatchAll mocks base method.
func (m *MockJetstreamKeyValue) WatchAll(arg0 context.Context, arg1 ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WatchAll", varargs...)
	ret0, _ := ret[0].(jetstream.KeyWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchAll indicates an expected call of WatchAll.
func (mr *MockJetstreamKeyValueMockRecorder) WatchAll(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchAll", reflect.TypeOf((*MockJetstreamKeyValue)(nil).WatchAll), varargs...)
}

// WatchFiltered mocks base method.
func (m *MockJetstreamKeyValue) WatchFiltered(arg0 context.Context, arg1 []string, arg2 ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WatchFiltered", varargs...)
	ret0, _ := ret[0].(jetstream.KeyWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchFiltered indicates an expected call of WatchFiltered.
func (mr *MockJetstreamKeyValueMockRecorder) WatchFiltered(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchFiltered", reflect.TypeOf((*MockJetstreamKeyValue)(nil).WatchFiltered), varargs...)
}

// MockJetstreamKeyValueEntry is a mock of KeyValueEntry interface.
type MockJetstreamKeyValueEntry struct {
	ctrl     *gomock.Controller
	recorder *MockJetstreamKeyValueEntryMockRecorder
}

// MockJetstreamKeyValueEntryMockRecorder is the mock recorder for MockJetstreamKeyValueEntry.
type MockJetstreamKeyValueEntryMockRecorder struct {
	mock *MockJetstreamKeyValueEntry
}

// NewMockJetstreamKeyValueEntry creates a new mock instance.
func NewMockJetstreamKeyValueEntry(ctrl *gomock.Controller) *MockJetstreamKeyValueEntry {
	mock := &MockJetstreamKeyValueEntry{ctrl: ctrl}
	mock.recorder = &MockJetstreamKeyValueEntryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJetstreamKeyValueEntry) EXPECT() *MockJetstreamKeyValueEntryMockRecorder {
	return m.recorder
}

// Bucket mocks base method.
func (m *MockJetstreamKeyValueEntry) Bucket() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bucket")
	ret0, _ := ret[0].(string)
	return ret0
}

// Bucket indicates an expected call of Bucket.
func (mr *MockJetstreamKeyValueEntryMockRecorder) Bucket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bucket", reflect.TypeOf((*MockJetstreamKeyValueEntry)(nil).Bucket))
}

// Created mocks base method.
func (m *MockJetstreamKeyValueEntry) Created() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Created")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Created indicates an expected call of Created.
func (mr *MockJetstreamKeyValueEntryMockRecorder) Created() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Created", reflect.TypeOf((*MockJetstreamKeyValueEntry)(nil).Created))
}

// Delta mocks base method.
func (m *MockJetstreamKeyValueEntry) Delta() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delta")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Delta indicates an expected call of Delta.
func (mr *MockJetstreamKeyValueEntryMockRecorder) Delta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delta", reflect.TypeOf((*MockJetstreamKeyValueEntry)(nil).Delta))
}

// Key mocks base method.
func (m *MockJetstreamKeyValueEntry) Key() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key")
	ret0, _ := ret[0].(string)
	return ret0
}

// Key indicates an expected call of Key.
func (mr *MockJetstreamKeyValueEntryMockRecorder) Key() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockJetstreamKeyValueEntry)(nil).Key))
}

// Operation mocks base method.
func (m *MockJetstreamKeyValueEntry) Operation() jetstream.KeyValueOp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operation")
	ret0, _ := ret[0].(jetstream.KeyValueOp)
	return ret0
}

// Operation indicates an expected call of Operation.
func (mr *MockJetstreamKeyValueEntryMockRecorder) Operation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operation", reflect.TypeOf((*MockJetstreamKeyValueEntry)(nil).Operation))
}

// Revision mocks base method.
func (m *MockJetstreamKeyValueEntry) Revision() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revision")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Revision indicates an expected call of Revision.
func (mr *MockJetstreamKeyValueEntryMockRecorder) Revision() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revision", reflect.TypeOf((*MockJetstreamKeyValueEntry)(nil).Revision))
}

// Value mocks base method.
func (m *MockJetstreamKeyValueEntry) Value() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockJetstreamKeyValueEntryMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockJetstreamKeyValueEntry)(nil).Value))
}

// MockJetstreamKeyWatcher is a mock of KeyWatcher interface.
type MockJetstreamKeyWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockJetstreamKeyWatcherMockRecorder
}

// MockJetstreamKeyWatcherMockRecorder is the mock recorder for MockJetstreamKeyWatcher.
type MockJetstreamKeyWatcherMockRecorder struct {
	mock *MockJetstreamKeyWatcher
}

// NewMockJetstreamKeyWatcher creates a new mock instance.
func NewMockJetstreamKeyWatcher(ctrl *gomock.Controller) *MockJetstreamKeyWatcher {
	mock := &MockJetstreamKeyWatcher{ctrl: ctrl}
	mock.recorder = &MockJetstreamKeyWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJetstreamKeyWatcher) EXPECT() *MockJetstreamKeyWatcherMockRecorder {
	return m.recorder
}

// Stop mocks base method.
func (m *MockJetstreamKeyWatcher) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockJetstreamKeyWatcherMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockJetstreamKeyWatcher)(nil).Stop))
}

// Updates mocks base method.
func (m *MockJetstreamKeyWatcher) Updates() <-chan jetstream.KeyValueEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates")
	ret0, _ := ret[0].(<-chan jetstream.KeyValueEntry)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockJetstreamKeyWatcherMockRecorder) Updates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockJetstreamKeyWatcher)(nil).Updates))
}
