// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nats-io/nkeys (interfaces: KeyPair)
//
// Generated by this command:
//
//	mockgen -destination=./nkeys.gen.go -package=mocks github.com/nats-io/nkeys KeyPair
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKeyPair is a mock of KeyPair interface.
type MockKeyPair struct {
	ctrl     *gomock.Controller
	recorder *MockKeyPairMockRecorder
	isgomock struct{}
}

// MockKeyPairMockRecorder is the mock recorder for MockKeyPair.
type MockKeyPairMockRecorder struct {
	mock *MockKeyPair
}

// NewMockKeyPair creates a new mock instance.
func NewMockKeyPair(ctrl *gomock.Controller) *MockKeyPair {
	mock := &MockKeyPair{ctrl: ctrl}
	mock.recorder = &MockKeyPairMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyPair) EXPECT() *MockKeyPairMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockKeyPair) Open(input []byte, sender string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", input, sender)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockKeyPairMockRecorder) Open(input, sender any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockKeyPair)(nil).Open), input, sender)
}

// PrivateKey mocks base method.
func (m *MockKeyPair) PrivateKey() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateKey")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivateKey indicates an expected call of PrivateKey.
func (mr *MockKeyPairMockRecorder) PrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateKey", reflect.TypeOf((*MockKeyPair)(nil).PrivateKey))
}

// PublicKey mocks base method.
func (m *MockKeyPair) PublicKey() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKey")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicKey indicates an expected call of PublicKey.
func (mr *MockKeyPairMockRecorder) PublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKey", reflect.TypeOf((*MockKeyPair)(nil).PublicKey))
}

// Seal mocks base method.
func (m *MockKeyPair) Seal(input []byte, recipient string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seal", input, recipient)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seal indicates an expected call of Seal.
func (mr *MockKeyPairMockRecorder) Seal(input, recipient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seal", reflect.TypeOf((*MockKeyPair)(nil).Seal), input, recipient)
}

// SealWithRand mocks base method.
func (m *MockKeyPair) SealWithRand(input []byte, recipient string, rr io.Reader) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SealWithRand", input, recipient, rr)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SealWithRand indicates an expected call of SealWithRand.
func (mr *MockKeyPairMockRecorder) SealWithRand(input, recipient, rr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SealWithRand", reflect.TypeOf((*MockKeyPair)(nil).SealWithRand), input, recipient, rr)
}

// Seed mocks base method.
func (m *MockKeyPair) Seed() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seed")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seed indicates an expected call of Seed.
func (mr *MockKeyPairMockRecorder) Seed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seed", reflect.TypeOf((*MockKeyPair)(nil).Seed))
}

// Sign mocks base method.
func (m *MockKeyPair) Sign(input []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockKeyPairMockRecorder) Sign(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockKeyPair)(nil).Sign), input)
}

// Verify mocks base method.
func (m *MockKeyPair) Verify(input, sig []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", input, sig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockKeyPairMockRecorder) Verify(input, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockKeyPair)(nil).Verify), input, sig)
}

// Wipe mocks base method.
func (m *MockKeyPair) Wipe() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wipe")
}

// Wipe indicates an expected call of Wipe.
func (mr *MockKeyPairMockRecorder) Wipe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wipe", reflect.TypeOf((*MockKeyPair)(nil).Wipe))
}
